### ISSUE TITLE
'Cannot call get_descendants on unsaved Location instances' error when merging new location and child location

### ISSUE THREAD

**Issue by duckw** [netboxlabs/netbox-branching#143]
### Plugin Version

0.5.0

### NetBox Version

4.1.1

### Python Version

3.12

### Steps to Reproduce

1. Add new branch
2. Activate new branch
3. Create new location to an existing site
4. Click 'Add Child Location'
5. Create the child location
6. Merge the branch
7. Check the merge job status

### Expected Behavior

Merge to be successful.

### Observed Behavior

Branch merge job shows the following:

{
    "log": [
        "Merging branch LOCTEST (branch_qv0723dh)",
        "Found 2 changes to merge",
        "Setting branch status to merging",
        "Applying change DCIM | location TEST1 created by admin using default",
        "Creating location <DeserializedObject: dcim.Location(pk=7875)>",
        "Applying change DCIM | location TEST2 created by admin using default",
        "Creating location <DeserializedObject: dcim.Location(pk=7876)>",
        "Cannot call get_descendants on unsaved Location instances"
    ]
}

**Comment by jeremystretch** [comment]
#17577 has been resolved and this issue should be fixed in NetBox v4.1.2.
