### ISSUE TITLE
Branch Creation: Job error - AttributeError("'NoneType' object has no attribute '_base_manager'")

### ISSUE THREAD

**Issue by xocoru** [netboxlabs/netbox-branching#187]
### Plugin Version

0.5.2

### NetBox Version

4.1.3

### Python Version

3.11.6

### Steps to Reproduce

Plugins:
netbox-topology-views -- 4.1.0
netbox-interface-synchronization -- 4.1.4
django3-auth-saml2               0.6.1
netbox-plugin-auth-saml2         2.3

Previously Netbox was update from 4.0.3 to 4.1.6
Installed Netbox Branching 0.5.2
Create a Branch and get this issue 
AttributeError("'NoneType' object has no attribute '_base_manager'")

### Expected Behavior

Branch should be created with no issues

### Observed Behavior

AttributeError("'NoneType' object has no attribute '_base_manager'")

there is no any details:
{
    "log": []
}

I don't know how to debug it properly.

**Comment by arthanson** [comment]
@xocoru Do you have the same plugins installed after the upgrade?  I'm wondering if this is related to https://github.com/netbox-community/netbox/issues/7149

**Comment by xocoru** [comment]
Yes, I didn't disable any of them.

**Comment by xocoru** [comment]
How can I enable logging for jobs? 


```
    'loggers': {
        'django': {
            'handlers': ['netbox_log'],
            'level': 'INFO',
        },
        'netbox': {
            'handlers': ['netbox_log'],
            'level': 'DEBUG',
        },
        'django_auth_ldap': {
            'handlers': ['netbox_auth_log'],
            'level': 'DEBUG',
        },
        'netbox_branching': {
            'handlers': ['netbox_branching'],
            'level': 'DEBUG',
        },
        'jobs': {
            'handlers': ['jobs'],
            'level': 'DEBUG',
        },
    },
```
There is nothing interesting

**Comment by xocoru** [comment]
I also cleared old changes
```
# python manage.py housekeeping
[*] Clearing expired authentication sessions
	Sessions cleared.
[*] Checking for expired changelog records
	Deleting 161603 expired records... Done.
[*] Checking for expired jobs
	No expired records found.
[*] Checking for latest release
	Skipping: RELEASE_CHECK_URL not set
Finished.
```

It didn't work

**Comment by xocoru** [comment]
Tried this:
`# python manage.py remove_stale_contenttypes`

It didn't help

**Comment by xocoru** [comment]
`# systemctl restart netbox-rq`

solved the problem
