### ISSUE TITLE
'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by PaulR282** [netboxlabs/netbox-branching#42]
### Plugin Version

v0.3.0

### NetBox Version

v4.1.0-beta1

### Python Version

3.11.6

### Steps to Reproduce

Go to Background Tasks and click on an ID or try to run a script

### Expected Behavior

Background Task should be shown

### Observed Behavior

`'str' object has no attribute '_meta'`

```
Error during template rendering
In template /opt/netbox/netbox/templates/generic/object.html, error at line 118
'str' object has no attribute '_meta'
```
```
108 	    <li class="nav-item">
109 	      <a class="nav-link{% if not tab %} active{% endif %}" href="{{ object.get_absolute_url }}">{{ object|meta:"verbose_name"|bettertitle }}</a>
110 	    </li>
111 	
112 	    {# Include tabs for registered model views #}
113 	    {% model_view_tabs object %}
114 	  </ul>
115 	{% endblock tabs %}
116 	
117 	{% block alerts %}
118 	  {% plugin_alerts object %}
119 	{% endblock alerts %}
120 	
121 	{% block content %}{% endblock %}
122 	
123 	{% block modals %}
124 	  {% include 'inc/htmx_modal.html' %}
125 	{% endblock modals %}
126 	
```

**Comment by PaulR282** [comment]
More context:
This is in a docker environment. If I don't have the plugin active, everything works normally. This only occurs with the plugin. I found this out because new branches are stuck at "provisioning" and the job runs forever. I see the Background task failed but I can't open it to see the reason because I get the described error.

**Comment by qspark-eliezerlp** [comment]
Also in a Docker deployment I see a similar error when navigating via the UI to a recently imported custom script:

> **Server Error**
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> ```
> <class 'AttributeError'>
> 
> 'str' object has no attribute '_meta'
> 
> Python version: 3.11.6
> NetBox version: 4.1.0-beta1
> Plugins: 
>   netbox_branching: 0.3.0
> ```
URL = https://netbox-beta-with-plugins/extras/scripts/3/




Netbox container logs:
```
netbox-1               | 172.x.x.x - - [15/Aug/2024:05:10:34 +0000] "GET /extras/scripts/3/ HTTP/1.1" 500 1651 "https://netbox-beta-with-plugins/extras/scripts/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
```
