### ISSUE TITLE
Unable to merge a branch with non-existing custom fields

### ISSUE THREAD

**Issue by peteeckel** [netboxlabs/netbox-branching#43]
### Plugin Version

0.3.0

### NetBox Version

4.1-beta1

### Python Version

3.11.5

### Steps to Reproduce

Disclaimer: I have only tested with NetBox DNS so far.

1. Create a branch
2. Perform some arbitrary changes in NetBox DNS
3. Try to merge the branch

### Expected Behavior

The branch is merged

### Observed Behavior

The branch status shows the following error message:

<img width="1154" alt="Screenshot 2024-08-14 at 11 38 14" src="https://github.com/user-attachments/assets/b2504076-2e59-40c7-b634-2ed0d75055cc">

When I look at the diffs, I see the following entry for the changes to the `View` object:

<img width="1108" alt="Screenshot 2024-08-14 at 11 46 24" src="https://github.com/user-attachments/assets/23ce0212-aef1-452a-83e4-621fbb1d680d">

The data shown under 'before' are all `None`, which is definitely not correct - the same is true for the other objects. The only exception is with deletes, where the before data correctly represents the status before the object was deleted.

**Comment by peteeckel** [comment]
Additional information:
```### NetBox interactive shell (dns.dev.hindenburgring.com)
### Python 3.11.5 | Django 5.0.7 | NetBox NetBox Community v4.1.0-beta1
### lsmodels() will show available models. Use help(<model>) for more info.
>>> from netbox_dns.models import View
>>> for view in View.objects.all():
...     print(view.custom_fields)
... 
<RestrictedQuerySet []>
<RestrictedQuerySet []>
<RestrictedQuerySet []>
>>> for view in View.objects.all():
...     print(view.custom_field_data)
... 
{}
{}
{}
```

**Comment by jeremystretch** [comment]
> 2. Perform some arbitrary changes in NetBox DNS

Please detail specifically what change you're making, so that we can reproduce it exactly.

**Comment by peteeckel** [comment]
OK, I failed to reproduce **exactly** this error with a fresh database, so I'll open another issue.
