### ISSUE TITLE
Can't Merge Branch When Interfaces Have Custom Fields

### ISSUE THREAD

**Issue by adparis99** [netboxlabs/netbox-branching#94]
### Plugin Version

0.4.0

### NetBox Version

4.1.0

### Python Version

3.10.12

### Steps to Reproduce

1. Create an optional custom field on the interface model
2. Create and activate a new branch
3. Create new interfaces (in my case associated with a few newly created devices). The custom field is _not_ populated.
4. Attempt to merge branch

### Expected Behavior

The branch should merge successfully.

### Observed Behavior

I receive essentially the same error mentioned in issue #80:
![image](https://github.com/user-attachments/assets/2025ddf5-7ca7-4708-89df-40df0ebbfe29)
```
{
    "log": [
        "Merging branch COR - New Equipment (branch_38u5jdzs)",
        "Found 247 changes to merge",
        "Setting branch status to merging",
        "Interface has no field named 'custom_fields'"
    ]
}
```

**Edit:** Added clarification that the custom field was not required nor populated for the newly created interfaces.
**Edit 2:** Added additional findings and steps to reproduce below.

**Comment by adparis99** [comment]
After some more trial and error, I've found a more specific set of **Steps to Reproduce**. It seems like if I generate those interfaces without making changes, merges go through. But if I adjust an attribute (the ones I've tested being `description` and `mac`), then I get the error above.

### Steps to Reproduce

1. Create an optional custom field on the interface model
2. Create and activate a new branch
3. Create new interfaces (in my case associated with a few newly created devices). The custom field is not populated.
4. Edit an attribute of the interface (for example, the description)
5. Attempt to merge branch

**Comment by adparis99** [comment]
One more thing I noticed in troubleshooting - based on the _Changes Ahead_ tab, it seems that when the objects are initially created in a branch, their `custom_felds` attribute is completely empty. It's not until I edit and save an interface that `custom_fields` are filled with the default _None_ value.

![image](https://github.com/user-attachments/assets/5b0db542-71ad-4915-9e42-c5efb2607b1c)

**Comment by jeremystretch** [comment]
Ok, I'm able to consistently reproduce this now by doing the following:

1. Create an optional custom field on the interface model
2. Create and activate a new branch
3. Edit an existing interface and set a value for the custom field
4. Attempt to merge the branch

This raises the exception:

```
FieldDoesNotExist("Interface has no field named 'custom_fields'")
```
