### ISSUE TITLE
Merged branch object still showing "This object has been modified in the following branches..."

### ISSUE THREAD

**Issue by arthanson** [netboxlabs/netbox-branching#99]
### Plugin Version

v0.4.0

### NetBox Version

v4.1.0

### Python Version

v3.12

### Steps to Reproduce

1. Create a New Branch
2. Activate the New Branch (Branch "A")
3. In the branch make an edit (i.e. Add a new site "Site BA"
4. Go to the branch and merge it
5. Go to the site you created

### Expected Behavior

No object modified in branch message should appear as the branch has been merged.

### Observed Behavior

You still see a "This object has been modified in the following branches"
![basite | NetBox 2024-09-09 13-50-02](https://github.com/user-attachments/assets/393c57df-a6cb-4204-9a51-4ff961c7a8b4)

**Comment by jeremystretch** [comment]
@arthanson I'm not able to reproduce this in `develop`. Can you check your steps again?

**Comment by arthanson** [comment]
Can't repro now, closing
